name: Build and Run Integration Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Sphinx
        run: sudo apt-get install python3-sphinx
      - name: Install our application with pipenv
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d
      - name: Use pipenv environment
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: shell
      - name: Make HTML
        run: cd docs && make html
      - name: Test Turtle Code Blocks in Contents and Top Level Elements
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run python tests/test_code_blocks.py
